<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvvr19z\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvvr19z/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXvvr19z.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXvvr19z\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXvvr19z\appProdProjectContainer([
    'container.build_hash' => 'Xvvr19z',
    'container.build_id' => '95744d0a',
    'container.build_time' => 1721296013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvvr19z');
